# Generated by Django 4.2.20 on 2025-04-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("foodmaster", "0006_profile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shared_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shares",
                to="foodmaster.post",
            ),
        ),
    ]
