# Generated by Django 4.2.20 on 2025-04-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodmaster", "0009_post_shared_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="shared_restaurant",
        ),
        migrations.AddField(
            model_name="post",
            name="shared_restaurant_place_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="place_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
