# Generated by Django 4.2.20 on 2025-04-09 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("foodmaster", "0010_remove_post_shared_restaurant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="shared_restaurant_place_id",
        ),
        migrations.AddField(
            model_name="post",
            name="shared_restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_posts",
                to="foodmaster.restaurant",
            ),
        ),
    ]
