# Generated by Django 4.2.20 on 2025-04-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodmaster", "0011_remove_post_shared_restaurant_place_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="shared_restaurant",
        ),
        migrations.AddField(
            model_name="post",
            name="shared_restaurant_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="shared_restaurant_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="shared_restaurant_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="shared_restaurant_place_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
