# Generated by Django 4.2.20 on 2025-04-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodmaster", "0012_remove_post_shared_restaurant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="shared_restaurant_lat",
        ),
        migrations.RemoveField(
            model_name="post",
            name="shared_restaurant_lng",
        ),
    ]
