# Generated by Django 4.2.20 on 2025-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodmaster", "0013_remove_post_shared_restaurant_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shared_restaurant_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
