# Generated by Django 4.2.20 on 2025-04-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodmaster", "0016_savedrecipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cuisine",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
