# Generated by Django 4.2.20 on 2025-04-15 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodmaster", "0017_post_cuisine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="cuisine",
            new_name="shared_cuisine",
        ),
    ]
