# Generated by Django 4.2.20 on 2025-04-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodmaster", "0018_rename_cuisine_post_shared_cuisine"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrecipe",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrestaurant",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
