# Generated by Django 4.2.20 on 2025-04-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodmaster", "0019_savedrecipe_photo_url_savedrestaurant_photo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedrestaurant",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="savedrestaurant",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant_photos/"
            ),
        ),
    ]
