# Generated by Django 4.2.20 on 2025-04-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodmaster", "0020_remove_savedrestaurant_photo_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedrestaurant",
            name="photo",
        ),
        migrations.AddField(
            model_name="savedrestaurant",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
